# Generated by Django 5.0.2 on 2024-03-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='proapp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
    ]
