# Generated by Django 5.0.2 on 2024-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discounted_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proapp',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
