# Generated by Django 5.0.2 on 2024-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('it', 'indoor toy'), ('ot', 'outdoor toy'), ('d', 'dolls'), ('t', 'teddy'), ('at', 'Action toy'), ('ct', 'combo toy')], max_length=2),
        ),
    ]
