# Generated by Django 5.0.2 on 2024-03-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IT', 'indoor toy'), ('OT', 'outdoor toy'), ('DT', 'dolls'), ('TT', 'teddy'), ('AT', 'Action toy'), ('CT', 'combo toy'), ('CC', 'cartoon character')], max_length=2),
        ),
    ]
